root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./src"
  entrypoint = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  exclude_file = []
  delay = 1000
  kill_delay = "0s"